server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
 